return {
	treesitter = {
		"vimdoc",
		"angular",
		"html",
		"css",
		"scss",
		"javascript",
		"typescript",
		"tsx",
		"lua",
		"json",
		"yaml",
		"markdown",
		"http",
	},
	lsp = {
		"ts_ls",
		"angularls",
		"html",
		"cssls",
		"tailwindcss",
		"lua_ls",
		"emmet_language_server",
	},
	tools = {
		"stylua",
		"prettierd",
		"prettier",
		"eslint_d",
	},
	formatters = {
		lua = { "stylua" },
		javascript = { "biome", "prettierd", "prettier", "eslint_d", stop_after_first = true },
		javascriptreact = { "biome", "prettierd", "prettier", "eslint_d", stop_after_first = true },
		typescript = { "biome", "prettierd", "prettier", "eslint_d", stop_after_first = true },
		typescriptreact = { "biome", "prettierd", "prettier", "eslint_d", stop_after_first = true },
		css = { "biome", "prettierd", "prettier", stop_after_first = true },
		scss = { "biome", "prettierd", "prettier", stop_after_first = true },
		html = { "prettierd", "prettier", stop_after_first = true },
		json = { "prettierd", "prettier", stop_after_first = true },
		yaml = { "prettierd", "prettier", stop_after_first = true },
		markdown = { "prettierd", "prettier", stop_after_first = true },
	},
}
